const markMass1 = 78;
const markHeight1 = 1.69;
const johnMass1 = 92;
const johnHeight1 = 1.95;
const markBMI1 = markMass1 / (markHeight1 ** 2);
const johnBMI1 = johnMass1 / (johnHeight1 ** 2);
const markHigherBMI1 = markBMI1 > johnBMI1;
console.log('Data 1');
console.log('BMI Mark:', markBMI1);
console.log('BMI John:', johnBMI1);
console.log('Mark có BMI cao hơn John không?', markHigherBMI1);
const markMass2 = 95;
const markHeight2 = 1.88;
const johnMass2 = 85;
const johnHeight2 = 1.76;
const markBMI2 = markMass2 / (markHeight2 * markHeight2);
const johnBMI2 = johnMass2 / (johnHeight2 * johnHeight2);
const markHigherBMI2 = markBMI2 > johnBMI2;
console.log('\nData 2');
console.log('BMI Mark:', markBMI2);
console.log('BMI John:', johnBMI2);
console.log('Mark có BMI cao hơn John không?', markHigherBMI2);